#!/bin/bash

# Script con instrucciones detalladas para crear cuenta en Dynu
# Ejecutar en Orange Pi o mostrar al usuario

echo "=== GUÍA COMPLETA: CREAR CUENTA EN DYNU ==="
echo ""
echo "Dynu es un servicio GRATUITO de DNS dinámico que te permite:"
echo "• Asignar un nombre de dominio fijo a tu IP dinámica"
echo "• Acceder a tus servicios sin recordar IPs que cambian"
echo "• Usar URLs como: http://tu-nombre.dynu.net en lugar de http://181.51.34.83"
echo ""

echo "PASO 1: ACCEDER AL SITIO WEB"
echo "============================="
echo "1. Abre tu navegador web"
echo "2. Ve a la dirección: https://www.dynu.com/"
echo "3. Asegúrate de que la página cargue correctamente"
echo ""

echo "PASO 2: REGISTRAR CUENTA GRATUITA"
echo "==================================="
echo "1. En la página principal, busca el botón 'Sign Up' (Registro)"
echo "2. Completa el formulario de registro:"
echo "   • Email: tu-email@ejemplo.com"
echo "   • Password: elige una contraseña segura"
echo "   • Confirma la contraseña"
echo "   • Acepta los términos y condiciones"
echo "3. Haz clic en 'Sign Up' para crear la cuenta"
echo ""

echo "PASO 3: VERIFICAR EMAIL"
echo "========================"
echo "1. Revisa tu bandeja de entrada del email que registraste"
echo "2. Busca un email de Dynu con asunto como 'Verify your email'"
echo "3. Haz clic en el enlace de verificación"
echo "4. Si no encuentras el email, revisa la carpeta de spam"
echo ""

echo "PASO 4: INICIAR SESIÓN"
echo "======================="
echo "1. Una vez verificado el email, regresa a https://www.dynu.com/"
echo "2. Haz clic en 'Sign In' (Iniciar Sesión)"
echo "3. Ingresa tu email y contraseña"
echo "4. Haz clic en 'Sign In'"
echo ""

echo "PASO 5: ACCEDER AL PANEL DE CONTROL"
echo "===================================="
echo "1. Después de iniciar sesión, verás tu panel de control"
echo "2. En el menú lateral izquierdo, busca 'DDNS Services'"
echo "3. Haz clic en 'DDNS Services'"
echo ""

echo "PASO 6: CREAR TU PRIMER HOSTNAME"
echo "=================================="
echo "1. En la página DDNS Services, haz clic en el botón 'Add'"
echo "2. Completa el formulario:"
echo "   • Hostname: elige un nombre único (ej: mini-cluster-arm)"
echo "   • Domain: selecciona 'dynu.net' (gratuito)"
echo "   • IP Address: deja en blanco (se actualizará automáticamente)"
echo "   • Location: selecciona tu ubicación aproximada"
echo "3. Haz clic en 'Save' para crear el hostname"
echo ""

echo "PASO 7: OBTENER CREDENCIALES DE API"
echo "===================================="
echo "1. En el menú lateral, ve a 'Account' > 'API Credentials'"
echo "2. Verás tu Username (tu email) y Password"
echo "3. Opcionalmente, puedes generar una API Key más segura:"
echo "   • Haz clic en 'Generate API Key'"
echo "   • Copia la API Key generada"
echo ""

echo "PASO 8: ANOTAR TUS DATOS"
echo "========================="
echo "Anótalos en un lugar seguro:"
echo "• Username: [tu-email@ejemplo.com]"
echo "• Password: [tu-contraseña] O API Key: [tu-api-key]"
echo "• Hostname completo: [tu-nombre.dynu.net]"
echo ""

echo "=== SIGUIENTE PASO ==="
echo ""
echo "Una vez que tengas tu cuenta y hostname creado,"
echo "ejecuta el script de instalación de Dynu:"
echo ""
echo "/root/setup-dynu-ddns.sh"
echo ""
echo "Luego configura el cliente con tus credenciales:"
echo ""
echo "dynu config set username TU_USERNAME password TU_PASSWORD"
echo ""
echo "O con API Key:"
echo ""
echo "dynu config set username TU_USERNAME apikey TU_API_KEY"
echo ""

echo "=== EJEMPLO FINAL ==="
echo ""
echo "Después de configurar, podrás acceder así:"
echo "• Keycloak: http://tu-nombre.dynu.net:8080"
echo "• PostgreSQL: tu-nombre.dynu.net:5432"
echo ""
echo "¡Sin preocuparte de que cambie tu IP!"
echo ""

echo "=== AYUDA ADICIONAL ==="
echo ""
echo "Si tienes problemas:"
echo "• Sitio web de Dynu: https://www.dynu.com/"
echo "• Documentación: https://www.dynu.com/en-US/DynamicDNS"
echo "• Soporte: support@dynu.com"
echo ""

echo "=== FIN DE LA GUÍA ==="