#!/bin/bash

# Script para configurar port forwarding en router Claro
# Ejecutar en Orange Pi

echo "=== CONFIGURACIÓN PORT FORWARDING - ROUTER CLARO ==="
echo ""
echo "Tu router Claro tiene IP: 192.168.1.1"
echo "IP de tu Orange Pi: 192.168.1.200"
echo ""

echo "PASO 1: ACCEDER AL ROUTER"
echo "=========================="
echo "1. Abre tu navegador web"
echo "2. Ve a: http://192.168.1.1"
echo "3. Usuario: admin (o el que tengas configurado)"
echo "4. Contraseña: la contraseña de tu router"
echo ""

echo "PASO 2: ENCONTRAR PORT FORWARDING"
echo "==================================="
echo "Busca una de estas opciones en el menú:"
echo "• 'Red' → 'NAT' → 'Port Forwarding'"
echo "• 'Avanzado' → 'NAT' → 'Port Forwarding'"
echo "• 'Firewall' → 'Port Forwarding'"
echo "• 'Configuración' → 'Port Forwarding'"
echo ""

echo "PASO 3: CONFIGURAR REGLAS"
echo "=========================="
echo "Crea DOS reglas de port forwarding:"
echo ""
echo "Regla 1 - Keycloak:"
echo "-------------------"
echo "• Nombre: Keycloak"
echo "• Puerto externo: 8080"
echo "• Puerto interno: 8080"
echo "• IP interna: 192.168.1.200"
echo "• Protocolo: TCP"
echo "• Habilitado: Sí"
echo ""
echo "Regla 2 - PostgreSQL:"
echo "----------------------"
echo "• Nombre: PostgreSQL"
echo "• Puerto externo: 5432"
echo "• Puerto interno: 5432"
echo "• IP interna: 192.168.1.200"
echo "• Protocolo: TCP"
echo "• Habilitado: Sí"
echo ""

echo "PASO 4: GUARDAR Y REINICIAR"
echo "============================"
echo "1. Haz clic en 'Aplicar' o 'Guardar'"
echo "2. Si el router lo pide, reinícialo"
echo "3. Espera 1-2 minutos para que se apliquen los cambios"
echo ""

echo "PASO 5: VERIFICAR CONFIGURACIÓN"
echo "================================"
echo "Después de configurar, ejecuta:"
echo ""
echo "/root/test-port-forwarding.sh"
echo ""
echo "O prueba manualmente desde otro dispositivo (NO en tu red local):"
echo ""
echo "curl http://otoro.ddnsfree.com:8080"
echo ""

echo "=== POSIBLES PROBLEMAS ==="
echo ""
echo "Si no funciona:"
echo "• Verifica que la IP interna (192.168.1.200) sea correcta"
echo "• Asegúrate de que los puertos no estén bloqueados por el ISP"
echo "• Prueba con puertos alternos (8081, 5433) si 8080/5432 no funcionan"
echo "• Desactiva temporalmente el firewall del router"
echo ""

echo "=== ACCESO FINAL ==="
echo ""
echo "Una vez configurado, podrás acceder:"
echo "• Keycloak: http://otoro.ddnsfree.com:8080"
echo "• PostgreSQL: otoro.ddnsfree.com:5432"
echo ""

echo "=== FIN DE INSTRUCCIONES ==="